feat: clear button template
ng-select/ng-select pull request #2281
Opened 2023-09-18 10:16 UTC by nubinub

Feature #2071 

Clear button template to customize clear button.

Sorry for the closed issue digging, but this is something I'd really like to have when using ng-select.

2024-04-29 20:18 UTC, osamagamal65 approved these changes

2024-05-23 21:17 UTC, pavankjadda requested changes

2024-05-23 21:17 UTC, pavankjadda commented on src/ng-select/lib/ng-select.component.html
> +            [ngTemplateOutlet]="clearButtonTemplate || defaultClearButtonTemplate">
Where is `clearButtonTemplate` defined?

2024-05-23 22:12 UTC, pavankjadda requested changes

2024-05-23 22:12 UTC, pavankjadda commented on src/ng-select/lib/ng-templates.directive.ts
> +    constructor(public template: TemplateRef<any>) { }
Why do we need this? We can pass template reference directly

2024-05-24 16:44 UTC, pavankjadda commented
Related to #2354

2024-05-26 02:58 UTC, pavankjadda approved these changes
Looks good now

2024-05-26 03:18 UTC, pavankjadda commented
@nubinub rebase with master and fix test cases

2024-06-07 02:50 UTC, pavankjadda commented
#2387  will take care of this

2024-06-07 02:50 UTC, closed without merging