Tab focus on clear input #2410
ng-select/ng-select pull request #2485
Opened 2024-12-11 03:28 UTC by SHKChan

This PR addresses the issue described in [#2410](https://github.com/ng-select/ng-select/issues/2410).

Following the approach discussed in the issue, I have implemented a new property, `tabFocusOnClear`. When `tabFocusOnClear` is set to false, it removes the `tabindex` property from the clear button.

Additionally, I have added a test case to ensure the functionality is properly validated.

I first updated my fork to sync it with the latest changes from the upstream repository and then pushed my commit to create this PR.

As I am new to contributing to open-source projects, I would greatly appreciate any feedback or suggestions for improvement.

Thank you for reviewing!

2024-12-27 19:54 UTC, pavankjadda requested changes

2024-12-27 19:54 UTC, pavankjadda commented on src/ng-select/lib/ng-select.component.ts
> +	@Input({ transform: booleanAttribute }) tabFocusOnClear: boolean = true;
@SHKChan convert this to signal `input`

2025-03-11 14:15 UTC, pavankjadda requested changes

2025-03-11 14:15 UTC, pavankjadda commented on src/ng-select/lib/ng-select.component.html
> +			  [attr.tabindex]="tabFocusOnClearButton() ? 0 : null"
why do we need two tabindexs here?

2025-04-09 00:57 UTC, pavankjadda commented
@SHKChan resolve conflicts and address issues?

2025-04-14 14:29 UTC, adambennett commented
@pavankjadda @SHKChan Is it possible we could add an option through the NgSelectConfig to support disabling this functionality globally?

2025-04-14 19:08 UTC, pavankjadda commented
closed in #2546 2546

2025-04-14 19:08 UTC, closed without merging